import { supabase } from '../lib/supabase';

export interface AuditLogData {
  userRole: string; // e.g., 'manager', 'hr', 'team_leader', 'tuqa'
  userEmail?: string;
  actionType: string; // e.g., 'CREATE_EMPLOYEE', 'UPDATE_RATING'
  details: string; // e.g., 'Added a new employee named Ali'
}

export const logActivity = async (data: AuditLogData) => {
  try {
    const { error } = await supabase
      .from('audit_logs')
      .insert([
        {
          user_role: data.userRole,
          user_email: data.userEmail || 'unknown',
          action_type: data.actionType,
          details: data.details,
          // created_at will be automatically generated by Supabase if configured correctly
        },
      ]);

    if (error) {
      console.error('Error logging activity to Supabase:', error);
    } else {
      console.log('Activity logged successfully:', data);
    }
  } catch (err) {
    console.error('Failed to log activity:', err);
  }
};
